KerasJson: example-keras-model-files/KERAS_3layer_batch_norm.json
KerasH5:   example-keras-model-files/KERAS_3layer_batch_norm_weights.h5
InputData: example-keras-model-files/KERAS_3layer_input_features.dat
OutputPredictions: example-keras-model-files/KERAS_3layer_batch_norm_predictions.dat
TruthLabels: example-keras-model-files/KERAS_3layer_truth_labels.dat
OutputDir: my-hls-test-3layer-batchnorm
ProjectName: myproject
XilinxPart: xcvu9p-fsgd2104-2-i
ClockPeriod: 5

IOType: io_parallel # options: io_serial/io_parallel
HLSConfig:
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 1